server:
  port: 8082

# todo :: move to application-test.yml
#spring:
#  datasource:
#    url: jdbc:h2:mem:demo
#    username: sa
#    password: password
#    driverClassName: org.h2.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#  h2:
#    console.enabled: true

management:
  endpoints:
    web:
      base-path: /

spring:
  ai:
    openai:
      api-key: "${OPENAI_KEY}"